# Generated by Django 4.2.21 on 2025-06-26 16:26

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Имя пользователя"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Владелец платформы"),
                            ("moderator", "Модератор платформы"),
                            ("store_owner", "Владелец магазина"),
                            ("store_admin", "Администратор магазина"),
                            ("user", "Пользователь"),
                            ("guest", "Гость"),
                        ],
                        default="user",
                        max_length=20,
                        verbose_name="Роль",
                    ),
                ),
                (
                    "role_icon",
                    models.CharField(
                        blank=True,
                        help_text="Персональный эмодзи-значок для обычных пользователей",
                        max_length=10,
                        null=True,
                        verbose_name="Персональный значок",
                    ),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Уникальный числовой ID пользователя в Telegram",
                        null=True,
                        unique=True,
                        verbose_name="Telegram ID",
                    ),
                ),
                (
                    "telegram_username",
                    models.CharField(
                        blank=True,
                        help_text="Ваш username в Telegram (без @)",
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Telegram Username",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Рекомендуемый размер: 300x300px",
                        null=True,
                        upload_to="avatars/",
                        verbose_name="Аватар",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Расскажите о себе (максимум 500 символов)",
                        max_length=500,
                        verbose_name="О себе",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Город, регион или страна",
                        max_length=100,
                        verbose_name="Местоположение",
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("beginner", "🌱 Новичок"),
                            ("intermediate", "🌿 Опытный"),
                            ("advanced", "🌳 Эксперт"),
                            ("master", "🏆 Мастер"),
                        ],
                        default="beginner",
                        help_text="Ваш уровень опыта в выращивании",
                        max_length=20,
                        verbose_name="Уровень опыта",
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        help_text="Ваш личный сайт или блог",
                        verbose_name="Веб-сайт",
                    ),
                ),
                (
                    "karma_points",
                    models.IntegerField(
                        default=0,
                        help_text="Очки за активность на платформе",
                        verbose_name="Очки кармы",
                    ),
                ),
                (
                    "followers_count",
                    models.IntegerField(
                        default=0, verbose_name="Количество подписчиков"
                    ),
                ),
                (
                    "following_count",
                    models.IntegerField(default=0, verbose_name="Количество подписок"),
                ),
                (
                    "posts_count",
                    models.IntegerField(default=0, verbose_name="Количество постов"),
                ),
                (
                    "photos_count",
                    models.IntegerField(
                        default=0, verbose_name="Количество фотографий"
                    ),
                ),
                (
                    "likes_given",
                    models.IntegerField(default=0, verbose_name="Поставлено лайков"),
                ),
                (
                    "likes_received",
                    models.IntegerField(default=0, verbose_name="Получено лайков"),
                ),
                (
                    "comments_count",
                    models.IntegerField(
                        default=0, verbose_name="Количество комментариев"
                    ),
                ),
                (
                    "is_profile_public",
                    models.BooleanField(
                        default=True,
                        help_text="Разрешить другим пользователям видеть ваш профиль",
                        verbose_name="Публичный профиль",
                    ),
                ),
                (
                    "show_experience_level",
                    models.BooleanField(
                        default=True, verbose_name="Показывать уровень опыта"
                    ),
                ),
                (
                    "show_karma",
                    models.BooleanField(default=True, verbose_name="Показывать карму"),
                ),
                (
                    "show_statistics",
                    models.BooleanField(
                        default=True, verbose_name="Показывать статистику"
                    ),
                ),
                (
                    "allow_direct_messages",
                    models.BooleanField(
                        default=True, verbose_name="Разрешить личные сообщения"
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(default=True, verbose_name="Email уведомления"),
                ),
                (
                    "notify_new_followers",
                    models.BooleanField(
                        default=True, verbose_name="Уведомления о новых подписчиках"
                    ),
                ),
                (
                    "notify_likes",
                    models.BooleanField(
                        default=True, verbose_name="Уведомления о лайках"
                    ),
                ),
                (
                    "notify_comments",
                    models.BooleanField(
                        default=True, verbose_name="Уведомления о комментариях"
                    ),
                ),
                (
                    "is_banned",
                    models.BooleanField(
                        default=False,
                        help_text="Забаненные пользователи не могут войти в систему",
                        verbose_name="Забанен",
                    ),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последняя активность"
                    ),
                ),
                (
                    "account_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания аккаунта"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "temp_password",
                    models.BooleanField(
                        default=False,
                        help_text="Отмечено, если пользователь использует временный пароль",
                        verbose_name="Временный пароль",
                    ),
                ),
                (
                    "password_expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Дата и время истечения временного пароля",
                        null=True,
                        verbose_name="Пароль истекает",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата рождения"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[
                            ("ru", "Русский"),
                            ("en", "English"),
                            ("ua", "Українська"),
                        ],
                        default="ru",
                        max_length=10,
                        verbose_name="Предпочитаемый язык",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Europe/Moscow",
                        max_length=50,
                        verbose_name="Часовой пояс",
                    ),
                ),
                (
                    "theme_preference",
                    models.CharField(
                        choices=[
                            ("light", "Светлая"),
                            ("dark", "Темная"),
                            ("auto", "Автоматически"),
                        ],
                        default="light",
                        max_length=10,
                        verbose_name="Тема оформления",
                    ),
                ),
                (
                    "favorite_strains",
                    models.TextField(
                        blank=True,
                        help_text="Перечислите ваши любимые сорта через запятую",
                        verbose_name="Любимые сорта",
                    ),
                ),
                (
                    "growing_style",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("indoor", "🏠 Индор"),
                            ("outdoor", "🌞 Аутдор"),
                            ("greenhouse", "🏡 Теплица"),
                            ("mixed", "🔄 Смешанный"),
                        ],
                        max_length=50,
                        verbose_name="Стиль выращивания",
                    ),
                ),
                (
                    "equipment",
                    models.TextField(
                        blank=True,
                        help_text="Опишите ваше оборудование для выращивания",
                        verbose_name="Оборудование",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_extra",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расширенный профиль",
                "verbose_name_plural": "Расширенные профили",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("like", "👍 Лайк"),
                            ("comment", "💬 Комментарий"),
                            ("follow", "👥 Подписка"),
                            ("mention", "📢 Упоминание"),
                            ("system", "⚙️ Системное"),
                            ("order", "🛍️ Новый заказ"),
                            ("chat_message", "💬 Новое сообщение в чате"),
                        ],
                        max_length=20,
                        verbose_name="Тип уведомления",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("message", models.TextField(verbose_name="Сообщение")),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="Прочитано"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Получатель",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Отправитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BanRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ban_type",
                    models.CharField(
                        choices=[
                            ("global", "Global Ban"),
                            ("chat", "Chat Ban"),
                            ("gallery", "Gallery Ban"),
                            ("growlogs", "Grow Logs Ban"),
                        ],
                        default="global",
                        max_length=20,
                        verbose_name="Ban Type",
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="Reason")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave empty for permanent ban",
                        null=True,
                        verbose_name="Expires at",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "banned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bans_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ban Record",
                "verbose_name_plural": "Ban Records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserFollow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата подписки"
                    ),
                ),
                (
                    "followed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="На кого подписан",
                    ),
                ),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Подписчик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подписка",
                "verbose_name_plural": "Подписки",
                "ordering": ["-created_at"],
                "unique_together": {("follower", "followed")},
            },
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes_given_new",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лайк",
                "verbose_name_plural": "Лайки",
                "ordering": ["-created_at"],
                "unique_together": {("user", "content_type", "object_id")},
            },
        ),
    ]
