# Generated by Django 4.2.21 on 2025-05-22 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_banned",
            field=models.BooleanField(
                default=False,
                help_text="Banned users cannot log in to the system",
                verbose_name="Banned",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("admin", "Admin"),
                    ("store_owner", "Store Owner"),
                    ("store_admin", "Store Admin"),
                    ("user", "User"),
                    ("guest", "Guest"),
                ],
                default="user",
                max_length=20,
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="telegram_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Telegram ID",
            ),
        ),
        migrations.CreateModel(
            name="BanRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ban_type",
                    models.CharField(
                        choices=[
                            ("global", "Global Ban"),
                            ("chat", "Chat Ban"),
                            ("gallery", "Gallery Ban"),
                            ("growlogs", "Grow Logs Ban"),
                        ],
                        default="global",
                        max_length=20,
                        verbose_name="Ban Type",
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="Reason")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave empty for permanent ban",
                        null=True,
                        verbose_name="Expires at",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "banned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bans_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ban Record",
                "verbose_name_plural": "Ban Records",
                "ordering": ["-created_at"],
            },
        ),
    ]
