# Generated by Django 4.2.21 on 2025-05-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_account_created_user_allow_direct_messages_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="password_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Дата и время истечения временного пароля",
                null=True,
                verbose_name="Пароль истекает",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="temp_password",
            field=models.BooleanField(
                default=False,
                help_text="Отмечено, если пользователь использует временный пароль",
                verbose_name="Временный пароль",
            ),
        ),
    ]
