# Generated by Django 4.2.21 on 2025-05-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="Уникальный числовой ID пользователя в Telegram",
                null=True,
                unique=True,
                verbose_name="Telegram ID",
            ),
        ),
    ]
