# Generated by Django 4.2.21 on 2025-05-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_user_telegram_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("like", "👍 Лайк"),
                    ("comment", "💬 Комментарий"),
                    ("follow", "👥 Подписка"),
                    ("mention", "📢 Упоминание"),
                    ("system", "⚙️ Системное"),
                    ("order", "🛍️ Новый заказ"),
                    ("chat_message", "💬 Новое сообщение в чате"),
                ],
                max_length=20,
                verbose_name="Тип уведомления",
            ),
        ),
    ]
