# Generated by Django 4.2.21 on 2025-06-16 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role_icon",
            field=models.CharField(
                blank=True,
                help_text="Персональный эмодзи-значок для обычных пользователей",
                max_length=10,
                null=True,
                verbose_name="Персональный значок",
            ),
        ),
    ]
