version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: magic_beans_db
      POSTGRES_USER: magic_beans_user
      POSTGRES_PASSWORD: magic_beans_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: compose/local/django/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://magic_beans_user:magic_beans_password@postgres:5432/magic_beans_db
      DJANGO_SETTINGS_MODULE: config.settings.local
    env_file:
      - .env

volumes:
  postgres_data:
