version: '3'

services:
  postgres:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=besedka
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: besedka_local_web
    command: daphne -b 0.0.0.0 -p 8001 config.asgi:application
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    env_file:
      - ./.env
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:6
    ports:
      - "6379:6379"

volumes:
  postgres_data:
