# Generated by Django 4.2.21 on 2025-05-30 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import news.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название категории"),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="URL слаг"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Категория новостей",
                "verbose_name_plural": "Категории новостей",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NewsSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название источника"),
                ),
                ("url", models.URLField(verbose_name="URL источника")),
                (
                    "parsing_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Включен для парсинга"
                    ),
                ),
                (
                    "last_parsed",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последний парсинг"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Источник новостей",
                "verbose_name_plural": "Источники новостей",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ParsingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Начало парсинга"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Окончание парсинга"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Выполняется"),
                            ("completed", "Завершен"),
                            ("failed", "Ошибка"),
                        ],
                        default="running",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "total_sources",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Всего источников"
                    ),
                ),
                (
                    "successful_sources",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Успешных источников"
                    ),
                ),
                (
                    "total_articles",
                    models.PositiveIntegerField(default=0, verbose_name="Всего статей"),
                ),
                (
                    "new_articles",
                    models.PositiveIntegerField(default=0, verbose_name="Новых статей"),
                ),
                ("errors", models.TextField(blank=True, verbose_name="Ошибки")),
                ("notes", models.TextField(blank=True, verbose_name="Заметки")),
            ],
            options={
                "verbose_name": "Лог парсинга",
                "verbose_name_plural": "Логи парсинга",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ParsedNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Заголовок")),
                (
                    "original_title",
                    models.CharField(
                        max_length=500, verbose_name="Оригинальный заголовок"
                    ),
                ),
                ("content", models.TextField(verbose_name="Содержание")),
                (
                    "original_content",
                    models.TextField(verbose_name="Оригинальное содержание"),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True, max_length=1000, verbose_name="Краткое описание"
                    ),
                ),
                ("original_url", models.URLField(verbose_name="Оригинальная ссылка")),
                (
                    "image_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL изображения"
                    ),
                ),
                (
                    "parsed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата парсинга"
                    ),
                ),
                (
                    "original_date",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Дата оригинальной публикации",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает модерации"),
                            ("approved", "Одобрено"),
                            ("rejected", "Отклонено"),
                            ("published", "Опубликовано"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "moderated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата модерации"
                    ),
                ),
                (
                    "moderation_notes",
                    models.TextField(blank=True, verbose_name="Заметки модератора"),
                ),
                (
                    "edited_title",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="Отредактированный заголовок",
                    ),
                ),
                (
                    "edited_content",
                    models.TextField(
                        blank=True, verbose_name="Отредактированное содержание"
                    ),
                ),
                (
                    "edited_summary",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        verbose_name="Отредактированное описание",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="news.newscategory",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "moderated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Модератор",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="news.newssource",
                        verbose_name="Источник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Спарсенная новость",
                "verbose_name_plural": "Спарсенные новости",
                "ordering": ["-parsed_at"],
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Заголовок")),
                (
                    "slug",
                    models.SlugField(
                        max_length=500, unique=True, verbose_name="URL слаг"
                    ),
                ),
                (
                    "summary",
                    models.TextField(max_length=1000, verbose_name="Краткое описание"),
                ),
                ("content", models.TextField(verbose_name="Содержание")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=news.models.news_image_upload_path,
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "image_alt",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Alt текст изображения"
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="META описание"
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="META ключевые слова"
                    ),
                ),
                (
                    "original_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Оригинальная ссылка"
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество просмотров"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата публикации",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликовано"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Рекомендуемая"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="news.newscategory",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "parsed_news",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="news.parsednews",
                        verbose_name="Спарсенная новость",
                    ),
                ),
            ],
            options={
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
                "ordering": ["-published_at"],
            },
        ),
    ]
