# Generated by Django 4.2.21 on 2025-06-08 12:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_newscategory_newssource_parsinglog_parsednews_news"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="content",
        ),
        migrations.AddField(
            model_name="comment",
            name="text",
            field=models.TextField(
                blank=True,
                default=None,
                null=True,
                validators=[django.core.validators.MinLengthValidator(3)],
                verbose_name="Комментарий",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
    ]
