# Generated by Django 4.2.21 on 2025-06-15 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("news", "0003_remove_comment_content_comment_text_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="reaction",
            name="unique_post_reaction_per_user",
        ),
        migrations.RemoveConstraint(
            model_name="reaction",
            name="unique_comment_reaction_per_user",
        ),
        migrations.RemoveIndex(
            model_name="reaction",
            name="news_reacti_post_id_16a7ab_idx",
        ),
        migrations.RemoveIndex(
            model_name="reaction",
            name="news_reacti_comment_42ef0a_idx",
        ),
        migrations.RemoveField(
            model_name="reaction",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="reaction",
            name="post",
        ),
        migrations.AddField(
            model_name="reaction",
            name="content_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                verbose_name="Тип контента",
            ),
        ),
        migrations.AddField(
            model_name="reaction",
            name="object_id",
            field=models.PositiveIntegerField(null=True, verbose_name="ID объекта"),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="reaction_type",
            field=models.CharField(
                choices=[("like", "👍 Лайк")],
                default="like",
                max_length=10,
                verbose_name="Тип реакции",
            ),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddIndex(
            model_name="reaction",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="news_reacti_content_439ee8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reaction",
            index=models.Index(fields=["user"], name="news_reacti_user_id_fe87cd_idx"),
        ),
        migrations.AddConstraint(
            model_name="reaction",
            constraint=models.UniqueConstraint(
                fields=("content_type", "object_id", "user"),
                name="unique_reaction_per_user_and_object",
            ),
        ),
    ]
