# Generated by Django 4.2.21 on 2025-06-15 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_remove_reaction_unique_post_reaction_per_user_and_more"),
    ]

    operations = []
