# Generated by Django 4.2.21 on 2025-06-15 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("news", "0005_auto_20250615_2341"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="reaction",
            name="unique_reaction_per_user_and_object",
        ),
        migrations.RemoveIndex(
            model_name="reaction",
            name="news_reacti_content_439ee8_idx",
        ),
        migrations.RemoveIndex(
            model_name="reaction",
            name="news_reacti_user_id_fe87cd_idx",
        ),
        migrations.RemoveField(
            model_name="reaction",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="reaction",
            name="object_id",
        ),
        migrations.AddField(
            model_name="reaction",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="news.comment",
                verbose_name="Комментарий",
            ),
        ),
        migrations.AddField(
            model_name="reaction",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="news.post",
                verbose_name="Пост",
            ),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="reaction_type",
            field=models.CharField(
                choices=[
                    ("like", "👍"),
                    ("dislike", "👎"),
                    ("love", "❤️"),
                    ("laugh", "😂"),
                    ("wow", "😮"),
                    ("sad", "😢"),
                    ("angry", "😠"),
                ],
                max_length=10,
                verbose_name="Тип реакции",
            ),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddIndex(
            model_name="reaction",
            index=models.Index(
                fields=["post", "reaction_type"], name="news_reacti_post_id_16a7ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reaction",
            index=models.Index(
                fields=["comment", "reaction_type"],
                name="news_reacti_comment_42ef0a_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="reaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("post__isnull", False)),
                fields=("post", "user"),
                name="unique_post_reaction_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="reaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("comment__isnull", False)),
                fields=("comment", "user"),
                name="unique_comment_reaction_per_user",
            ),
        ),
    ]
