# Generated by Django 4.2.21 on 2025-05-21 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("add", "Добавление"),
                            ("edit", "Редактирование"),
                            ("delete", "Удаление"),
                            ("view", "Просмотр"),
                            ("login", "Вход"),
                            ("logout", "Выход"),
                        ],
                        max_length=20,
                        verbose_name="Тип действия",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время действия"
                    ),
                ),
                (
                    "model_name",
                    models.CharField(max_length=100, verbose_name="Название модели"),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ID объекта"
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(
                        max_length=255, verbose_name="Представление объекта"
                    ),
                ),
                ("details", models.TextField(blank=True, verbose_name="Детали")),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="action_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись журнала",
                "verbose_name_plural": "Журнал действий",
                "ordering": ["-timestamp"],
            },
        ),
    ]
