# Generated by Django 4.2.21 on 2025-05-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("add", "Добавление"),
                    ("edit", "Редактирование"),
                    ("delete", "Удаление"),
                    ("view", "Просмотр"),
                    ("login", "Вход"),
                    ("logout", "Выход"),
                    ("temp_password_created", "Создан временный пароль"),
                ],
                max_length=30,
                verbose_name="Тип действия",
            ),
        ),
    ]
