# Generated by Django 4.2.21 on 2025-05-21 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gallery", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("growlogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="photocomment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photo_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="photocomment",
            name="photo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="gallery.photo",
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="growlog",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="photos",
                to="growlogs.growlog",
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="growlog_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="photos",
                to="growlogs.growlogentry",
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_photos", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
