# Generated by Django 4.2.21 on 2025-05-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активное"),
        ),
        migrations.AlterField(
            model_name="photo",
            name="is_public",
            field=models.BooleanField(default=True, verbose_name="Публичное"),
        ),
    ]
