# Generated by Django 4.2.21 on 2025-06-08 12:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gallery", "0003_photo_is_active_alter_photo_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="photocomment",
            name="is_edited",
            field=models.BooleanField(default=False, verbose_name="Отредактирован"),
        ),
        migrations.AddField(
            model_name="photocomment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="gallery.photocomment",
                verbose_name="Родительский комментарий",
            ),
        ),
        migrations.AlterField(
            model_name="photocomment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="photocomment",
            name="text",
            field=models.TextField(
                blank=True,
                default=None,
                null=True,
                validators=[django.core.validators.MinLengthValidator(3)],
                verbose_name="Комментарий",
            ),
        ),
    ]
