# Generated by Django 4.2.21 on 2025-06-12 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0004_photocomment_is_edited_photocomment_parent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="views_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Просмотры"),
        ),
    ]
