# Generated by Django 4.2.21 on 2025-06-15 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0005_photo_views_count"),
    ]

    operations = []
