# Generated by Django 4.2.21 on 2025-06-16 00:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gallery", "0006_auto_20250615_2352"),
    ]

    operations = [
        # Пытаемся создать поле likes, если его нет
        migrations.RunSQL(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'gallery_photo_likes') THEN
                    CREATE TABLE gallery_photo_likes (
                        id serial PRIMARY KEY,
                        photo_id bigint NOT NULL REFERENCES gallery_photo(id) ON DELETE CASCADE,
                        user_id bigint NOT NULL REFERENCES users_user(id) ON DELETE CASCADE,
                        UNIQUE(photo_id, user_id)
                    );
                    CREATE INDEX gallery_photo_likes_photo_id_idx ON gallery_photo_likes(photo_id);
                    CREATE INDEX gallery_photo_likes_user_id_idx ON gallery_photo_likes(user_id);
                END IF;
            END $$;
            """,
            reverse_sql="DROP TABLE IF EXISTS gallery_photo_likes;"
        ),
    ]
