# Generated by Django 4.2.21 on 2025-05-21 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SeedBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="seedbanks/",
                        verbose_name="Logo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seed Bank",
                "verbose_name_plural": "Seed Banks",
            },
        ),
        migrations.CreateModel(
            name="Strain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("description", models.TextField(verbose_name="Description")),
                ("genetics", models.CharField(max_length=255, verbose_name="Genetics")),
                (
                    "flowering_time",
                    models.PositiveIntegerField(verbose_name="Flowering Time (weeks)"),
                ),
                (
                    "thc_content",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="THC Content"
                    ),
                ),
                (
                    "cbd_content",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="CBD Content"
                    ),
                ),
                (
                    "effect",
                    models.CharField(blank=True, max_length=255, verbose_name="Effect"),
                ),
                (
                    "flavor",
                    models.CharField(blank=True, max_length=255, verbose_name="Flavor"),
                ),
                (
                    "breeder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strains",
                        to="magicbeans_store.seedbank",
                    ),
                ),
            ],
            options={
                "verbose_name": "Strain",
                "verbose_name_plural": "Strains",
            },
        ),
        migrations.CreateModel(
            name="StockItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "seeds_count",
                    models.PositiveIntegerField(verbose_name="Seeds Count"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price"
                    ),
                ),
                (
                    "in_stock",
                    models.BooleanField(default=True, verbose_name="In Stock"),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Discount %",
                    ),
                ),
                (
                    "strain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_items",
                        to="magicbeans_store.strain",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Item",
                "verbose_name_plural": "Stock Items",
            },
        ),
    ]
