# Generated by Django 4.2.21 on 2025-05-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("magicbeans_store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="seedbank",
            name="is_visible",
            field=models.BooleanField(
                default=True,
                help_text="If unchecked, this seed bank will be hidden from customers",
                verbose_name="Visible",
            ),
        ),
        migrations.AddField(
            model_name="strain",
            name="is_visible",
            field=models.BooleanField(
                default=True,
                help_text="If unchecked, this strain will be hidden from customers",
                verbose_name="Visible",
            ),
        ),
        migrations.AddField(
            model_name="strain",
            name="strain_type",
            field=models.CharField(
                choices=[
                    ("auto", "Autoflowering"),
                    ("photo", "Photoperiod"),
                    ("regular", "Regular"),
                    ("cbd", "CBD"),
                ],
                default="photo",
                max_length=10,
                verbose_name="Strain Type",
            ),
        ),
    ]
