# Generated by Django 4.2.21 on 2025-05-22 20:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("magicbeans_store", "0002_seedbank_is_visible_strain_is_visible_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Код купона"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Процент скидки",
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Максимальное количество использований"
                    ),
                ),
                (
                    "uses_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество использований"
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="Дата начала")),
                ("end_date", models.DateTimeField(verbose_name="Дата окончания")),
                (
                    "min_order_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Минимальная сумма заказа",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
            ],
            options={
                "verbose_name": "Купон",
                "verbose_name_plural": "Купоны",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("current", "Текущий остаток"),
                            ("movement", "Движение товара"),
                            ("low_stock", "Низкий остаток"),
                            ("custom", "Пользовательский"),
                        ],
                        default="current",
                        max_length=20,
                        verbose_name="Тип отчета",
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="Дата начала")),
                ("end_date", models.DateTimeField(verbose_name="Дата окончания")),
                (
                    "total_items",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Всего товаров"
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Общая стоимость",
                    ),
                ),
                (
                    "low_stock_threshold",
                    models.PositiveIntegerField(
                        default=5, verbose_name="Порог низкого остатка"
                    ),
                ),
                (
                    "report_data",
                    models.JSONField(
                        default=dict,
                        help_text="Детальные данные отчета в формате JSON",
                        verbose_name="Данные отчета",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
            ],
            options={
                "verbose_name": "Отчет по складу",
                "verbose_name_plural": "Отчеты по складу",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shipping_address", models.TextField(verbose_name="Адрес доставки")),
                (
                    "shipping_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Стоимость доставки",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Общая сумма"
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, verbose_name="Комментарий к заказу"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "color",
                    models.CharField(
                        default="#000000",
                        help_text="HEX код цвета",
                        max_length=7,
                        verbose_name="Цвет",
                    ),
                ),
                (
                    "is_final",
                    models.BooleanField(default=False, verbose_name="Финальный статус"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "Статус заказа",
                "verbose_name_plural": "Статусы заказов",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text="Инструкции, которые будут показаны клиенту при выборе этого способа оплаты",
                        verbose_name="Инструкции по оплате",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "Способ оплаты",
                "verbose_name_plural": "Способы оплаты",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Процент"),
                            ("fixed", "Фиксированная сумма"),
                        ],
                        default="percentage",
                        max_length=20,
                        verbose_name="Тип скидки",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Значение скидки",
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="Дата начала")),
                ("end_date", models.DateTimeField(verbose_name="Дата окончания")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
                ),
            ],
            options={
                "verbose_name": "Акция",
                "verbose_name_plural": "Акции",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="SalesReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily", "Ежедневный"),
                            ("weekly", "Еженедельный"),
                            ("monthly", "Ежемесячный"),
                            ("yearly", "Годовой"),
                            ("custom", "Пользовательский"),
                        ],
                        default="daily",
                        max_length=20,
                        verbose_name="Тип отчета",
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="Дата начала")),
                ("end_date", models.DateTimeField(verbose_name="Дата окончания")),
                (
                    "total_orders",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Всего заказов"
                    ),
                ),
                (
                    "total_sales",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Общая сумма продаж",
                    ),
                ),
                (
                    "average_order_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Средний чек",
                    ),
                ),
                (
                    "report_data",
                    models.JSONField(
                        default=dict,
                        help_text="Детальные данные отчета в формате JSON",
                        verbose_name="Данные отчета",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
            ],
            options={
                "verbose_name": "Отчет по продажам",
                "verbose_name_plural": "Отчеты по продажам",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="ShippingMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Стоимость",
                    ),
                ),
                (
                    "estimated_days",
                    models.CharField(
                        help_text="Например: 1-3 дня",
                        max_length=50,
                        verbose_name="Примерное время доставки",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "Способ доставки",
                "verbose_name_plural": "Способы доставки",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="StoreSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(max_length=255, verbose_name="Название сайта"),
                ),
                (
                    "store_email",
                    models.EmailField(max_length=254, verbose_name="Email магазина"),
                ),
                (
                    "store_phone",
                    models.CharField(max_length=50, verbose_name="Телефон магазина"),
                ),
                (
                    "store_address",
                    models.TextField(blank=True, verbose_name="Адрес магазина"),
                ),
                (
                    "min_order_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Минимальная сумма заказа",
                    ),
                ),
                (
                    "free_shipping_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Сумма для бесплатной доставки",
                    ),
                ),
                (
                    "maintenance_mode",
                    models.BooleanField(
                        default=False,
                        help_text="Если включено, сайт будет недоступен для посетителей",
                        verbose_name="Режим обслуживания",
                    ),
                ),
                (
                    "maintenance_message",
                    models.TextField(
                        blank=True, verbose_name="Сообщение о техническом обслуживании"
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки магазина",
                "verbose_name_plural": "Настройки магазина",
            },
        ),
        migrations.AlterModelOptions(
            name="seedbank",
            options={
                "ordering": ["name"],
                "verbose_name": "Сидбанк",
                "verbose_name_plural": "Сидбанки",
            },
        ),
        migrations.AlterModelOptions(
            name="stockitem",
            options={
                "ordering": ["strain", "seeds_count"],
                "verbose_name": "Товар на складе",
                "verbose_name_plural": "Товары на складе",
            },
        ),
        migrations.AlterModelOptions(
            name="strain",
            options={
                "ordering": ["seedbank", "name"],
                "verbose_name": "Сорт",
                "verbose_name_plural": "Сорта",
            },
        ),
        migrations.RemoveField(
            model_name="seedbank",
            name="is_visible",
        ),
        migrations.AddField(
            model_name="seedbank",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="quantity",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество на складе"
            ),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="sku",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Генерируется автоматически при сохранении",
                max_length=50,
                unique=True,
                verbose_name="Артикул",
            ),
        ),
        migrations.AddField(
            model_name="strain",
            name="height",
            field=models.CharField(blank=True, max_length=50, verbose_name="Высота"),
        ),
        migrations.AddField(
            model_name="strain",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AddField(
            model_name="strain",
            name="seedbank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="strains",
                to="magicbeans_store.seedbank",
                verbose_name="Сидбанк",
            ),
        ),
        migrations.AddField(
            model_name="strain",
            name="yield_indoor",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Урожайность (indoor)"
            ),
        ),
        migrations.AddField(
            model_name="strain",
            name="yield_outdoor",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Урожайность (outdoor)"
            ),
        ),
        migrations.AlterField(
            model_name="seedbank",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
        ),
        migrations.AlterField(
            model_name="seedbank",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="seedbank",
            name="logo",
            field=models.ImageField(
                blank=True,
                default=2,
                upload_to="seedbanks/logos/",
                verbose_name="Логотип",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="seedbank",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="seedbank",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
        ),
        migrations.AlterField(
            model_name="seedbank",
            name="website",
            field=models.URLField(blank=True, verbose_name="Веб-сайт"),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Цена",
            ),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="seeds_count",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Количество семян",
            ),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="strain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_items",
                to="magicbeans_store.strain",
                verbose_name="Сорт",
            ),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
        ),
        migrations.AlterField(
            model_name="strain",
            name="cbd_content",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Содержание CBD"
            ),
        ),
        migrations.AlterField(
            model_name="strain",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
        ),
        migrations.AlterField(
            model_name="strain",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="strain",
            name="effect",
            field=models.TextField(blank=True, verbose_name="Эффект"),
        ),
        migrations.AlterField(
            model_name="strain",
            name="flavor",
            field=models.TextField(blank=True, verbose_name="Вкус и аромат"),
        ),
        migrations.AlterField(
            model_name="strain",
            name="flowering_time",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Время цветения"
            ),
        ),
        migrations.AlterField(
            model_name="strain",
            name="genetics",
            field=models.CharField(blank=True, max_length=255, verbose_name="Генетика"),
        ),
        migrations.AlterField(
            model_name="strain",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="strain",
            name="strain_type",
            field=models.CharField(
                choices=[
                    ("regular", "Регулярный"),
                    ("feminized", "Феминизированный"),
                    ("autoflowering", "Автоцветущий"),
                ],
                default="regular",
                max_length=20,
                verbose_name="Тип",
            ),
        ),
        migrations.AlterField(
            model_name="strain",
            name="thc_content",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Содержание THC"
            ),
        ),
        migrations.AlterField(
            model_name="strain",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
        ),
        migrations.AlterUniqueTogether(
            name="stockitem",
            unique_together={("strain", "seeds_count")},
        ),
        migrations.AlterUniqueTogether(
            name="strain",
            unique_together={("seedbank", "name")},
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Количество")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена за единицу"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Общая стоимость"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="magicbeans_store.order",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "stock_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="magicbeans_store.stockitem",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция заказа",
                "verbose_name_plural": "Позиции заказа",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="magicbeans_store.paymentmethod",
                verbose_name="Способ оплаты",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="magicbeans_store.shippingmethod",
                verbose_name="Способ доставки",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="magicbeans_store.orderstatus",
                verbose_name="Статус",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.RemoveField(
            model_name="stockitem",
            name="discount",
        ),
        migrations.RemoveField(
            model_name="stockitem",
            name="in_stock",
        ),
        migrations.RemoveField(
            model_name="strain",
            name="breeder",
        ),
        migrations.RemoveField(
            model_name="strain",
            name="is_visible",
        ),
    ]
