# Generated by Django 4.2.21 on 2025-05-23 22:XX:XX

from django.db import migrations

def merge_effect_flavor_to_description(apps, schema_editor):
    """Объединяем поля effect и flavor в description"""
    Strain = apps.get_model('magicbeans_store', 'Strain')

    for strain in Strain.objects.all():
        # Создаем новое описание из существующих полей
        new_description = strain.description or ""

        if strain.effect:
            if new_description:
                new_description += "\n\n"
            new_description += f"Эффект: {strain.effect}"

        if strain.flavor:
            if new_description:
                new_description += "\n\n"
            new_description += f"Вкус и аромат: {strain.flavor}"

        strain.description = new_description
        strain.save()

def reverse_merge_effect_flavor(apps, schema_editor):
    """Обратная операция - ничего не делаем, данные сохранены в description"""
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('magicbeans_store', '0003_coupon_inventoryreport_order_orderstatus_and_more'),
    ]

    operations = [
        migrations.RunPython(
            merge_effect_flavor_to_description,
            reverse_merge_effect_flavor
        ),
    ]
