# Generated by Django 4.2.21 on 2025-05-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("magicbeans_store", "0004_merge_effect_flavor_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strain",
            name="cbd_content",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0-1", "0-1%"),
                    ("1-5", "1-5%"),
                    ("5-10", "5-10%"),
                    ("10-15", "10-15%"),
                    ("15-20", "15-20%"),
                    ("20+", "20%+"),
                    ("unknown", "Неизвестно"),
                ],
                default="unknown",
                max_length=20,
                verbose_name="Содержание CBD",
            ),
        ),
        migrations.AlterField(
            model_name="strain",
            name="flowering_time",
            field=models.CharField(
                blank=True,
                choices=[
                    ("6-8", "6-8 недель"),
                    ("8-10", "8-10 недель"),
                    ("10-12", "10-12 недель"),
                    ("12-14", "12-14 недель"),
                    ("14-16", "14-16 недель"),
                    ("16-20", "16-20 недель"),
                    ("20-25", "20-25 недель"),
                    ("25-30", "25-30 недель"),
                    ("30+", "30+ недель"),
                    ("auto", "Автоцвет"),
                    ("unknown", "Неизвестно"),
                ],
                default="unknown",
                max_length=20,
                verbose_name="Время цветения",
            ),
        ),
        migrations.AlterField(
            model_name="strain",
            name="thc_content",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0-5", "0-5%"),
                    ("5-10", "5-10%"),
                    ("10-15", "10-15%"),
                    ("15-20", "15-20%"),
                    ("20-25", "20-25%"),
                    ("25-30", "25-30%"),
                    ("30+", "30%+"),
                    ("unknown", "Неизвестно"),
                ],
                default="unknown",
                max_length=20,
                verbose_name="Содержание THC",
            ),
        ),
    ]
