# Generated by Django 4.2.21 on 2025-05-23 22:XX:XX

from django.db import migrations
import re

def migrate_strain_data(apps, schema_editor):
    """Приводим существующие данные к новым choices"""
    Strain = apps.get_model('magicbeans_store', 'Strain')

    for strain in Strain.objects.all():
        # Миграция THC content
        if strain.thc_content:
            thc_value = strain.thc_content.lower().replace('%', '').strip()
            if 'неизвестно' in thc_value or 'unknown' in thc_value or not thc_value:
                strain.thc_content = 'unknown'
            elif any(x in thc_value for x in ['0', '1', '2', '3', '4', '5']) and '5' not in thc_value[1:]:
                strain.thc_content = '0-5'
            elif any(x in thc_value for x in ['5', '6', '7', '8', '9']) and '10' not in thc_value:
                strain.thc_content = '5-10'
            elif any(x in thc_value for x in ['10', '11', '12', '13', '14']) and '15' not in thc_value:
                strain.thc_content = '10-15'
            elif any(x in thc_value for x in ['15', '16', '17', '18', '19']) and '20' not in thc_value:
                strain.thc_content = '15-20'
            elif any(x in thc_value for x in ['20', '21', '22', '23', '24']) and '25' not in thc_value:
                strain.thc_content = '20-25'
            elif any(x in thc_value for x in ['25', '26', '27', '28', '29']) and '30' not in thc_value:
                strain.thc_content = '25-30'
            elif any(x in thc_value for x in ['30', '31', '32', '33', '34', '35']) or '30+' in thc_value:
                strain.thc_content = '30+'
            else:
                strain.thc_content = 'unknown'
        else:
            strain.thc_content = 'unknown'

        # Миграция CBD content
        if strain.cbd_content:
            cbd_value = strain.cbd_content.lower().replace('%', '').strip()
            if 'неизвестно' in cbd_value or 'unknown' in cbd_value or not cbd_value:
                strain.cbd_content = 'unknown'
            elif any(x in cbd_value for x in ['0', '1']) and '1' not in cbd_value[1:]:
                strain.cbd_content = '0-1'
            elif any(x in cbd_value for x in ['1', '2', '3', '4']) and '5' not in cbd_value:
                strain.cbd_content = '1-5'
            elif any(x in cbd_value for x in ['5', '6', '7', '8', '9']) and '10' not in cbd_value:
                strain.cbd_content = '5-10'
            elif any(x in cbd_value for x in ['10', '11', '12', '13', '14']) and '15' not in cbd_value:
                strain.cbd_content = '10-15'
            elif any(x in cbd_value for x in ['15', '16', '17', '18', '19']) and '20' not in cbd_value:
                strain.cbd_content = '15-20'
            elif any(x in cbd_value for x in ['20', '21', '22', '23', '24', '25']) or '20+' in cbd_value:
                strain.cbd_content = '20+'
            else:
                strain.cbd_content = 'unknown'
        else:
            strain.cbd_content = 'unknown'

        # Миграция flowering time
        if strain.flowering_time:
            flowering_value = strain.flowering_time.lower().strip()
            if 'неизвестно' in flowering_value or 'unknown' in flowering_value or not flowering_value:
                strain.flowering_time = 'unknown'
            elif 'авто' in flowering_value or 'auto' in flowering_value:
                strain.flowering_time = 'auto'
            elif any(x in flowering_value for x in ['6', '7', '8']) and ('9' not in flowering_value and '10' not in flowering_value):
                strain.flowering_time = '6-8'
            elif any(x in flowering_value for x in ['8', '9', '10']) and ('11' not in flowering_value and '12' not in flowering_value):
                strain.flowering_time = '8-10'
            elif any(x in flowering_value for x in ['10', '11', '12']) and ('13' not in flowering_value and '14' not in flowering_value):
                strain.flowering_time = '10-12'
            elif any(x in flowering_value for x in ['12', '13', '14']) and ('15' not in flowering_value and '16' not in flowering_value):
                strain.flowering_time = '12-14'
            elif any(x in flowering_value for x in ['14', '15', '16']) and ('17' not in flowering_value and '20' not in flowering_value):
                strain.flowering_time = '14-16'
            elif any(x in flowering_value for x in ['16', '17', '18', '19', '20']) and ('21' not in flowering_value and '25' not in flowering_value):
                strain.flowering_time = '16-20'
            elif any(x in flowering_value for x in ['20', '21', '22', '23', '24', '25']) and ('26' not in flowering_value and '30' not in flowering_value):
                strain.flowering_time = '20-25'
            elif any(x in flowering_value for x in ['25', '26', '27', '28', '29', '30']) and '31' not in flowering_value:
                strain.flowering_time = '25-30'
            elif any(x in flowering_value for x in ['30', '31', '32', '33', '34', '35']) or '30+' in flowering_value:
                strain.flowering_time = '30+'
            else:
                strain.flowering_time = 'unknown'
        else:
            strain.flowering_time = 'unknown'

        strain.save()

def reverse_migrate_strain_data(apps, schema_editor):
    """Обратная миграция - ничего не делаем, данные остаются в новом формате"""
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('magicbeans_store', '0005_update_strain_choices'),
    ]

    operations = [
        migrations.RunPython(
            migrate_strain_data,
            reverse_migrate_strain_data
        ),
    ]
