# Generated by Django 4.2.21 on 2025-05-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("magicbeans_store", "0006_migrate_existing_strain_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strain",
            name="cbd_content",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0-0.5", "0-0.5%"),
                    ("0.5-1", "0.5-1%"),
                    ("1-1.5", "1-1.5%"),
                    ("1.5-2", "1.5-2%"),
                    ("2-2.5", "2-2.5%"),
                    ("2.5-3", "2.5-3%"),
                    ("3+", "3%+"),
                    ("unknown", "Неизвестно"),
                ],
                default="unknown",
                max_length=20,
                verbose_name="Содержание CBD",
            ),
        ),
        migrations.AlterField(
            model_name="strain",
            name="flowering_time",
            field=models.CharField(
                blank=True,
                choices=[
                    ("6-8", "6-8 недель"),
                    ("8-10", "8-10 недель"),
                    ("10-12", "10-12 недель"),
                    ("12+", "12+ недель"),
                    ("auto", "Автоцвет"),
                    ("unknown", "Неизвестно"),
                ],
                default="unknown",
                max_length=20,
                verbose_name="Время цветения",
            ),
        ),
    ]
