# Generated by Django 4.2.21 on 2025-05-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("magicbeans_store", "0008_update_existing_cbd_flowering_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seedbank",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Виден"),
        ),
        migrations.AlterField(
            model_name="strain",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Виден"),
        ),
    ]
