# Generated by Django 4.2.21 on 2025-05-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("magicbeans_store", "0010_add_cart_and_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="seedbank",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, verbose_name="Slug"),
        ),
    ]
