# Generated by Django 4.2.21 on 2025-05-25 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("magicbeans_store", "0011_add_seedbank_slug_step1"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        max_length=255, verbose_name="Полное имя получателя"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=30, verbose_name="Номер телефона"),
                ),
                (
                    "address_line_1",
                    models.CharField(
                        max_length=255, verbose_name="Адрес (улица, дом, квартира)"
                    ),
                ),
                (
                    "address_line_2",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Адрес (дополнительно)",
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Город")),
                (
                    "state_province_region",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Область/Край/Республика",
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(max_length=20, verbose_name="Почтовый индекс"),
                ),
                ("country", models.CharField(max_length=100, verbose_name="Страна")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Основной адрес"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_addresses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Адрес доставки",
                "verbose_name_plural": "Адреса доставки",
                "ordering": ["-is_default", "-updated_at"],
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='orders',
                to='magicbeans_store.shippingaddress',
                verbose_name='Адрес доставки',
            ),
        ),
        # Старая операция AlterField закомментирована или удалена
        # migrations.AlterField(
        #     model_name="order",
        #     name="shipping_address",
        #     field=models.ForeignKey(
        #         blank=True,
        #         null=True,
        #         on_delete=django.db.models.deletion.SET_NULL,
        #         related_name="orders",
        #         to="magicbeans_store.shippingaddress",
        #         verbose_name="Адрес доставки",
        #     ),
        # ),
    ]
