# Generated by Django 4.2.21 on 2025-05-26 17:12

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("magicbeans_store", "0012_shippingaddress_alter_order_shipping_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="applied_coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="magicbeans_store.coupon",
                verbose_name="Примененный купон",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Сумма скидки",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="applied_coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="magicbeans_store.coupon",
                verbose_name="Примененный купон",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Сумма скидки",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="subtotal_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Сумма товаров (до скидки)",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                verbose_name="Общая сумма (с учетом скидки и доставки)",
            ),
        ),
    ]
