# Generated by Django 4.2.21 on 2025-05-26 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("magicbeans_store", "0014_cart_session_key_alter_cart_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="guest_address_line_1",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Адрес гостя (улица, дом)",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="guest_address_line_2",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Адрес гостя (дополнительно)",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="guest_city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Город гостя"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="guest_country",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Страна гостя"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="guest_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email гостя"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="guest_full_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Полное имя гостя"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="guest_phone_number",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Телефон гостя"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="guest_postal_code",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Почтовый индекс гостя",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="guest_state_province_region",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Область/Край гостя"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Способ оплаты"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="magicbeans_store.shippingaddress",
                verbose_name="Адрес доставки (для зарегистрированных)",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
