# Generated by Django 4.2.21 on 2025-05-26 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("magicbeans_store", "0016_alter_order_shipping_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="shipping_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="magicbeans_store.shippingmethod",
                verbose_name="Способ доставки",
            ),
        ),
    ]
