# Generated by Django 4.2.21 on 2025-05-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("magicbeans_store", "0018_change_payment_method_to_fk"),
    ]

    operations = [
        migrations.CreateModel(
            name="SBPSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        help_text="Например: Сбербанк, ВТБ, Тинькофф",
                        max_length=200,
                        verbose_name="Название банка",
                    ),
                ),
                (
                    "account_holder",
                    models.CharField(
                        help_text="ФИО или название организации",
                        max_length=200,
                        verbose_name="Получатель платежа",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Номер телефона, привязанный к СБП",
                        max_length=20,
                        verbose_name="Номер телефона для СБП",
                    ),
                ),
                (
                    "bank_account",
                    models.CharField(
                        blank=True,
                        help_text="Номер банковского счета (опционально)",
                        max_length=50,
                        verbose_name="Номер счета",
                    ),
                ),
                (
                    "bik",
                    models.CharField(
                        blank=True,
                        help_text="БИК банка (опционально)",
                        max_length=9,
                        verbose_name="БИК банка",
                    ),
                ),
                (
                    "inn",
                    models.CharField(
                        blank=True,
                        help_text="ИНН получателя (опционально)",
                        max_length=12,
                        verbose_name="ИНН",
                    ),
                ),
                (
                    "payment_instructions",
                    models.TextField(
                        default="Для оплаты заказа через СБП:\n1. Наш менеджер свяжется с вами и предоставит реквизиты для оплаты\n2. Откройте приложение вашего банка\n3. Найдите функцию 'Переводы' или 'СБП'\n4. Введите номер телефона получателя или отсканируйте QR-код\n5. Укажите сумму заказа и подтвердите платеж\n6. Сообщите менеджеру о совершенном платеже",
                        help_text="Инструкции, которые будут показаны клиенту при выборе СБП",
                        verbose_name="Инструкции по оплате",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Показывать ли эти настройки клиентам",
                        verbose_name="Активны",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Настройки СБП",
                "verbose_name_plural": "Настройки СБП",
            },
        ),
    ]
