# Generated by Django 4.2.21 on 2025-05-27 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("magicbeans_store", "0019_sbpsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="StrainImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Изображение товара",
                        upload_to="strains/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, verbose_name="Основное изображение"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Описание изображения для доступности",
                        max_length=255,
                        verbose_name="Альтернативный текст",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "strain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="magicbeans_store.strain",
                        verbose_name="Сорт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение сорта",
                "verbose_name_plural": "Изображения сортов",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="strainimage",
            constraint=models.UniqueConstraint(
                fields=("strain", "order"), name="unique_strain_image_order"
            ),
        ),
    ]
