# Generated by Django 4.2.21 on 2025-05-28 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VIPChatMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invited_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата приглашения"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Активно ли членство в VIP-чате",
                        verbose_name="Активное членство",
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата принятия"
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        help_text="Пользователь, который отправил приглашение",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vip_invitations_sent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пригласил",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Членство в VIP-чате",
                "verbose_name_plural": "Членства в VIP-чатах",
            },
        ),
        migrations.CreateModel(
            name="VIPChatRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="VIP Беседка",
                        help_text="Название VIP-чата",
                        max_length=100,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="Приватный VIP-чат для избранных участников",
                        help_text="Описание VIP-чата",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Включен ли VIP-чат",
                        verbose_name="Активен",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Изменено"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Пользователь, создавший VIP-чат",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        help_text="Участники VIP-чата",
                        related_name="vip_chats",
                        through="chat.VIPChatMembership",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Участники",
                    ),
                ),
                (
                    "room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vip_chat_room",
                        to="chat.room",
                        verbose_name="Комната",
                    ),
                ),
            ],
            options={
                "verbose_name": "VIP-чат",
                "verbose_name_plural": "VIP-чаты",
            },
        ),
        migrations.AddField(
            model_name="vipchatmembership",
            name="vip_chat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="chat.vipchatroom",
                verbose_name="VIP-чат",
            ),
        ),
        migrations.CreateModel(
            name="GlobalChatRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Общий чат",
                        help_text="Название общего чата",
                        max_length=100,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="Общий чат для всех пользователей платформы Беседка",
                        help_text="Описание общего чата",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Включен ли общий чат",
                        verbose_name="Активен",
                    ),
                ),
                (
                    "auto_add_users",
                    models.BooleanField(
                        default=True,
                        help_text="Автоматически добавлять новых пользователей в общий чат",
                        verbose_name="Автодобавление пользователей",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Изменено"),
                ),
                (
                    "room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="global_chat_room",
                        to="chat.room",
                        verbose_name="Комната",
                    ),
                ),
            ],
            options={
                "verbose_name": "Общий чат",
                "verbose_name_plural": "Общие чаты",
            },
        ),
        migrations.AlterUniqueTogether(
            name="vipchatmembership",
            unique_together={("vip_chat", "user")},
        ),
    ]
