# Generated by Django 4.2.21 on 2025-06-28 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="edited_at",
            field=models.DateTimeField(
                blank=True, help_text="Когда было отредактировано", null=True
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="edited_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Кто отредактировал сообщение",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="edited_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="is_deleted",
            field=models.BooleanField(
                default=False, help_text="Сообщение помечено как удаленное"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="is_edited",
            field=models.BooleanField(
                default=False, help_text="Сообщение было отредактировано"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="is_forwarded",
            field=models.BooleanField(
                default=False, help_text="Сообщение является пересланным"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="original_message_id",
            field=models.CharField(
                blank=True,
                help_text="ID оригинального сообщения при пересылке",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
