# Generated by Django 4.2.21 on 2025-07-02 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0004_add_message_reactions"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserChatPosition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "last_read_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Время последнего прочтения сообщений в этом чате",
                        verbose_name="Последнее время прочтения",
                    ),
                ),
                (
                    "last_message_id",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID последнего сообщения, которое пользователь точно прочитал",
                        null=True,
                        verbose_name="ID последнего прочитанного сообщения",
                    ),
                ),
                (
                    "unread_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Кешированное количество непрочитанных сообщений для быстрого доступа",
                        verbose_name="Количество непрочитанных",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Время последнего обновления позиции",
                        verbose_name="Обновлено",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_positions",
                        to="chat.room",
                        verbose_name="Комната",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_positions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция пользователя в чате",
                "verbose_name_plural": "Позиции пользователей в чатах",
                "indexes": [
                    models.Index(
                        fields=["user", "room"], name="chat_userch_user_id_232c5c_idx"
                    ),
                    models.Index(
                        fields=["last_read_at"], name="chat_userch_last_re_299368_idx"
                    ),
                    models.Index(
                        fields=["unread_count"], name="chat_userch_unread__1b858b_idx"
                    ),
                ],
                "unique_together": {("user", "room")},
            },
        ),
    ]
