# Generated by Django 4.2.21 on 2025-07-03 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_add_user_chat_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userchatposition",
            name="last_read_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Время последнего прочтения сообщений в этом чате. None для новых пользователей.",
                null=True,
                verbose_name="Последнее время прочтения",
            ),
        ),
    ]
