# Generated by Django 4.2.21 on 2025-07-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_alter_userchatposition_last_read_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userchatposition",
            name="last_visit_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Время последнего визита в чат для определения правильной позиции",
                null=True,
                verbose_name="Последний визит",
            ),
        ),
        migrations.AddField(
            model_name="userchatposition",
            name="personal_notifications_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Кешированное количество персональных уведомлений (ответы + упоминания)",
                verbose_name="Количество персональных уведомлений",
            ),
        ),
        migrations.AddIndex(
            model_name="userchatposition",
            index=models.Index(
                fields=["personal_notifications_count"],
                name="chat_userch_persona_6297b2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userchatposition",
            index=models.Index(
                fields=["last_visit_at"], name="chat_userch_last_vi_8d0f7d_idx"
            ),
        ),
    ]
