# Generated by Django 4.2.21 on 2025-07-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_add_personal_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="userchatposition",
            name="last_visible_message_id",
            field=models.IntegerField(
                blank=True, help_text="ID последнего видимого сообщения", null=True
            ),
        ),
        migrations.AddField(
            model_name="userchatposition",
            name="scroll_position_percent",
            field=models.FloatField(
                default=0.0,
                help_text="Процент прокрутки чата (0.0 - начало, 1.0 - конец)",
            ),
        ),
    ]
