# Generated by Django 4.2.21 on 2025-06-26 16:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("magicbeans_store", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrowLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Логотип или главное фото гроу-репорта",
                        null=True,
                        upload_to="growlogs/logos/",
                        verbose_name="Логотип",
                    ),
                ),
                (
                    "strain_custom",
                    models.CharField(
                        blank=True,
                        help_text="Название сорта если его нет в магазине",
                        max_length=255,
                        verbose_name="Название сорта",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Дата начала")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("indoor", "Индор"),
                            ("outdoor", "Аутдор"),
                            ("greenhouse", "Теплица"),
                        ],
                        default="indoor",
                        max_length=20,
                        verbose_name="Среда выращивания",
                    ),
                ),
                (
                    "medium",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Субстрат"
                    ),
                ),
                ("nutrients", models.TextField(blank=True, verbose_name="Удобрения")),
                (
                    "lighting",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Освещение"
                    ),
                ),
                (
                    "container_size",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Размер контейнера"
                    ),
                ),
                (
                    "setup_description",
                    models.TextField(verbose_name="Описание установки"),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True,
                        help_text="Краткое описание для карточки",
                        max_length=500,
                        verbose_name="Краткое описание",
                    ),
                ),
                ("goals", models.TextField(blank=True, verbose_name="Цели")),
                (
                    "current_stage",
                    models.CharField(
                        choices=[
                            ("germination", "Проращивание"),
                            ("seedling", "Рассада"),
                            ("vegetative", "Вегетация"),
                            ("flowering", "Цветение"),
                            ("harvest", "Харвест"),
                            ("curing", "Пролечка"),
                            ("completed", "Завершено"),
                        ],
                        default="germination",
                        max_length=20,
                        verbose_name="Текущая стадия",
                    ),
                ),
                (
                    "yield_actual",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Фактический урожай (г)",
                    ),
                ),
                (
                    "yield_expected",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Ожидаемый урожай (г)",
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(default=0, verbose_name="Просмотры"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="Публичный"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активный"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "grower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="growlogs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="liked_growlogs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "strain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="growlogs",
                        to="magicbeans_store.strain",
                    ),
                ),
            ],
            options={
                "verbose_name": "Гроу-репорт",
                "verbose_name_plural": "Гроу-репорты",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GrowLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("day", models.PositiveIntegerField(verbose_name="День")),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("germination", "Проращивание"),
                            ("seedling", "Рассада"),
                            ("vegetative", "Вегетация"),
                            ("flowering", "Цветение"),
                            ("harvest", "Харвест"),
                            ("curing", "Пролечка"),
                            ("completed", "Завершено"),
                        ],
                        default="germination",
                        max_length=20,
                        verbose_name="Стадия",
                    ),
                ),
                (
                    "activities",
                    models.TextField(
                        blank=True,
                        help_text="Полив, подкормка, тренировка, наблюдения...",
                        verbose_name="Что сделано",
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Температура (°C)",
                    ),
                ),
                (
                    "humidity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Влажность (%)",
                    ),
                ),
                (
                    "ph",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        verbose_name="pH",
                    ),
                ),
                (
                    "ec",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="EC (мС/см)",
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="Высота (см)",
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="Ширина (см)",
                    ),
                ),
                (
                    "water_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Полив (л)",
                    ),
                ),
                (
                    "nutrients_used",
                    models.TextField(
                        blank=True, verbose_name="Использованные удобрения"
                    ),
                ),
                (
                    "growlog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="growlogs.growlog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись гроу-репорта",
                "verbose_name_plural": "Записи гроу-репортов",
                "ordering": ["day"],
                "unique_together": {("growlog", "day")},
            },
        ),
        migrations.CreateModel(
            name="GrowLogEntryPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="growlogs/entries/", verbose_name="Photo"
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=255, verbose_name="Title"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entry_photos",
                        to="growlogs.growlogentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entry Photo",
                "verbose_name_plural": "Entry Photos",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="GrowLogEntryComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True,
                        default=None,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(3)],
                        verbose_name="Комментарий",
                    ),
                ),
                (
                    "is_edited",
                    models.BooleanField(default=False, verbose_name="Отредактирован"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="growlogs.growlogentry",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="growlogs.growlogentrycomment",
                        verbose_name="Родительский комментарий",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entry Comment",
                "verbose_name_plural": "Entry Comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="GrowLogComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True,
                        default=None,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(3)],
                        verbose_name="Комментарий",
                    ),
                ),
                (
                    "is_edited",
                    models.BooleanField(default=False, verbose_name="Отредактирован"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "growlog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="growlogs.growlog",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="growlogs.growlogcomment",
                        verbose_name="Родительский комментарий",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grow Log Comment",
                "verbose_name_plural": "Grow Log Comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="GrowLogEntryLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="growlogs.growlogentry",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="growlog_entry_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Entry Like",
                "verbose_name_plural": "Entry Likes",
                "unique_together": {("entry", "user")},
            },
        ),
    ]
