# Generated by Django 4.2.21 on 2025-05-21 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("magicbeans_store", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("growlogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="growlog",
            name="grower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="growlogs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="growlog",
            name="strain",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="growlogs",
                to="magicbeans_store.strain",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="growlogentry",
            unique_together={("growlog", "day")},
        ),
    ]
