# Generated by Django 4.2.21 on 2025-05-24 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('growlogs', '0002_initial'),
    ]

    operations = [
    ]
