# Generated by Django 4.2.21 on 2025-05-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("growlogs", "0004_remove_growlogentry_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="growlog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Grow Log",
                "verbose_name_plural": "Grow Logs",
            },
        ),
        migrations.AddField(
            model_name="growlog",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активный"),
        ),
        migrations.AlterField(
            model_name="growlog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="growlog",
            name="is_public",
            field=models.BooleanField(default=True, verbose_name="Публичный"),
        ),
        migrations.AlterField(
            model_name="growlog",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
    ]
