# Generated by Django 4.2.21 on 2025-05-25 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("growlogs", "0005_alter_growlog_options_growlog_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="growlog",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Логотип или главное фото гроу-репорта",
                null=True,
                upload_to="growlogs/logos/",
                verbose_name="Logo",
            ),
        ),
        migrations.AddField(
            model_name="growlog",
            name="short_description",
            field=models.CharField(
                blank=True,
                help_text="Краткое описание для карточки",
                max_length=500,
                verbose_name="Short Description",
            ),
        ),
        migrations.CreateModel(
            name="GrowLogEntryPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="growlogs/entries/", verbose_name="Photo"
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=255, verbose_name="Title"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entry_photos",
                        to="growlogs.growlogentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entry Photo",
                "verbose_name_plural": "Entry Photos",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
