# Generated by Django 4.2.21 on 2025-05-29 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("magicbeans_store", "0020_strainimage_strainimage_unique_strain_image_order"),
        ("growlogs", "0007_growlogentrycomment_growlogentrylike"),
    ]

    operations = [
        migrations.AddField(
            model_name="growlog",
            name="strain_custom",
            field=models.CharField(
                blank=True,
                help_text="Название сорта если его нет в магазине",
                max_length=255,
                verbose_name="Custom Strain Name",
            ),
        ),
        migrations.AlterField(
            model_name="growlog",
            name="strain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="growlogs",
                to="magicbeans_store.strain",
            ),
        ),
    ]
