# Generated by Django 4.2.21 on 2025-05-29 16:29

from django.db import migrations, models


def merge_notes_and_activities(apps, schema_editor):
    """Объединяем поля notes и activities в одно поле activities"""
    GrowLogEntry = apps.get_model('growlogs', 'GrowLogEntry')

    for entry in GrowLogEntry.objects.all():
        # Поле notes уже не существует, поэтому просто проверяем activities
        if not hasattr(entry, 'activities') or not entry.activities:
            # Если activities пустое, ставим заглушку
            entry.activities = "Наблюдения..."
            entry.save()


def reverse_merge_notes_and_activities(apps, schema_editor):
    """Обратная операция - разделяем обратно (если нужно откатить)"""
    # В случае отката просто оставляем все в activities
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("growlogs", "0008_growlog_strain_custom_alter_growlog_strain"),
    ]

    operations = [
        # 1. Сначала объединяем данные
        migrations.RunPython(merge_notes_and_activities, reverse_merge_notes_and_activities),

        # 2. Обновляем поле activities
        migrations.AlterField(
            model_name='growlogentry',
            name='activities',
            field=models.TextField(blank=True, help_text='Полив, подкормка, тренировка, наблюдения...', verbose_name='Что сделано'),
        ),

        # 3. Обновляем verbose_name полей GrowLog
        migrations.AlterField(
            model_name='growlog',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='growlog',
            name='logo',
            field=models.ImageField(blank=True, help_text='Логотип или главное фото гроу-репорта', null=True, upload_to='growlogs/logos/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='growlog',
            name='strain_custom',
            field=models.CharField(blank=True, help_text='Название сорта если его нет в магазине', max_length=255, verbose_name='Название сорта'),
        ),
        migrations.AlterField(
            model_name='growlog',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='growlog',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='growlog',
            name='environment',
            field=models.CharField(choices=[('indoor', 'Индор'), ('outdoor', 'Аутдор'), ('greenhouse', 'Теплица')], default='indoor', max_length=20, verbose_name='Среда выращивания'),
        ),
        migrations.AlterField(
            model_name='growlog',
            name='medium',
            field=models.CharField(blank=True, max_length=255, verbose_name='Субстрат'),
        ),
        migrations.AlterField(
            model_name='growlog',
            name='nutrients',
            field=models.TextField(blank=True, verbose_name='Удобрения'),
        ),
        migrations.AlterField(
            model_name='growlog',
            name='lighting',
            field=models.CharField(blank=True, max_length=255, verbose_name='Освещение'),
        ),
        migrations.AlterField(
            model_name='growlog',
            name='container_size',
            field=models.CharField(blank=True, max_length=100, verbose_name='Размер контейнера'),
        ),
        migrations.AlterField(
            model_name='growlog',
            name='setup_description',
            field=models.TextField(verbose_name='Описание установки'),
        ),
        migrations.AlterField(
            model_name='growlog',
            name='short_description',
            field=models.CharField(blank=True, help_text='Краткое описание для карточки', max_length=500, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='growlog',
            name='goals',
            field=models.TextField(blank=True, verbose_name='Цели'),
        ),
        migrations.AlterField(
            model_name='growlog',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Дополнительные заметки'),
        ),
        migrations.AlterField(
            model_name='growlog',
            name='current_stage',
            field=models.CharField(choices=[('germination', 'Проращивание'), ('seedling', 'Рассада'), ('vegetative', 'Вегетация'), ('flowering', 'Цветение'), ('harvest', 'Харвест'), ('curing', 'Пролечка'), ('completed', 'Завершено')], default='germination', max_length=20, verbose_name='Текущая стадия'),
        ),
        migrations.AlterField(
            model_name='growlog',
            name='yield_actual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Фактический урожай (г)'),
        ),
        migrations.AlterField(
            model_name='growlog',
            name='yield_expected',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ожидаемый урожай (г)'),
        ),
        migrations.AlterField(
            model_name='growlog',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),

        # 4. Обновляем verbose_name полей GrowLogEntry
        migrations.AlterField(
            model_name='growlogentry',
            name='day',
            field=models.PositiveIntegerField(verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='growlogentry',
            name='stage',
            field=models.CharField(choices=[('germination', 'Проращивание'), ('seedling', 'Рассада'), ('vegetative', 'Вегетация'), ('flowering', 'Цветение'), ('harvest', 'Харвест'), ('curing', 'Пролечка'), ('completed', 'Завершено')], default='germination', max_length=20, verbose_name='Стадия'),
        ),
        migrations.AlterField(
            model_name='growlogentry',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Температура (°C)'),
        ),
        migrations.AlterField(
            model_name='growlogentry',
            name='humidity',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Влажность (%)'),
        ),
        migrations.AlterField(
            model_name='growlogentry',
            name='ph',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='pH'),
        ),
        migrations.AlterField(
            model_name='growlogentry',
            name='ec',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='EC (мС/см)'),
        ),
        migrations.AlterField(
            model_name='growlogentry',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Высота (см)'),
        ),
        migrations.AlterField(
            model_name='growlogentry',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Ширина (см)'),
        ),
        migrations.AlterField(
            model_name='growlogentry',
            name='water_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Полив (л)'),
        ),
        migrations.AlterField(
            model_name='growlogentry',
            name='nutrients_used',
            field=models.TextField(blank=True, verbose_name='Использованные удобрения'),
        ),

        # 5. Обновляем Meta для моделей
        migrations.AlterModelOptions(
            name='growlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Гроу-репорт', 'verbose_name_plural': 'Гроу-репорты'},
        ),
        migrations.AlterModelOptions(
            name='growlogentry',
            options={'ordering': ['day'], 'verbose_name': 'Запись гроу-репорта', 'verbose_name_plural': 'Записи гроу-репортов'},
        ),
    ]
