# Generated by Django 4.2.21 on 2025-05-29 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("growlogs", "0009_auto_20250529_1629"),
    ]

    operations = []
