# Generated by Django 4.2.21 on 2025-05-29 20:02

from django.db import migrations, connection


def check_and_remove_notes_field(apps, schema_editor):
    """Проверяем и удаляем поле notes если оно существует"""
    with connection.cursor() as cursor:
        try:
            # Проверяем существует ли поле notes (PostgreSQL синтаксис)
            cursor.execute("""
                SELECT column_name
                FROM information_schema.columns
                WHERE table_name = 'growlogs_growlogentry'
                AND column_name = 'notes'
            """)
            result = cursor.fetchone()

            if result:
                print("Поле notes найдено, удаляем...")
                # Удаляем поле notes (PostgreSQL синтаксис)
                cursor.execute("ALTER TABLE growlogs_growlogentry DROP COLUMN IF EXISTS notes")
                print("Поле notes успешно удалено")
            else:
                print("Поле notes не найдено в таблице")
        except Exception as e:
            print(f"Ошибка при проверке/удалении поля notes: {e}")


def reverse_notes_field(apps, schema_editor):
    """Обратная операция - ничего не делаем"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("growlogs", "0010_remove_notes_field"),
    ]

    operations = [
        migrations.RunPython(check_and_remove_notes_field, reverse_notes_field),
    ]
