# Generated by Django 4.2.21 on 2025-05-29 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("growlogs", "0012_auto_20250529_2344"),
        ("growlogs", "0012_final_notes_cleanup"),
    ]

    operations = []
