# Generated by Django 4.2.7 on 2025-06-08 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('growlogs', '0013_merge_20250530_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='growlogcomment',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='Отредактирован'),
        ),
        migrations.AddField(
            model_name='growlogcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='growlogs.growlogcomment', verbose_name='Родительский комментарий'),
        ),
        migrations.AddField(
            model_name='growlogentrycomment',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='Отредактирован'),
        ),
        migrations.AddField(
            model_name='growlogentrycomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='growlogs.growlogentrycomment', verbose_name='Родительский комментарий'),
        ),
        migrations.AlterField(
            model_name='growlogcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='growlogcomment',
            name='text',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='growlogentrycomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='growlogentrycomment',
            name='text',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Комментарий'),
        ),
    ]
