# Generated by Django 4.2.21 on 2025-06-15 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("growlogs", "0014_growlogcomment_is_edited_parent_and_more"),
    ]

    operations = []
