# Generated by Django 4.2.21 on 2025-06-15 21:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("growlogs", "0015_auto_20250615_2344"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="growlogentry",
        #     name="notes",
        # ),  # Закомментировано - поле уже было удалено в предыдущих миграциях
        migrations.AlterField(
            model_name="growlogcomment",
            name="text",
            field=models.TextField(
                blank=True,
                default=None,
                null=True,
                validators=[django.core.validators.MinLengthValidator(3)],
                verbose_name="Комментарий",
            ),
        ),
        migrations.AlterField(
            model_name="growlogentrycomment",
            name="text",
            field=models.TextField(
                blank=True,
                default=None,
                null=True,
                validators=[django.core.validators.MinLengthValidator(3)],
                verbose_name="Комментарий",
            ),
        ),
    ]
