# Generated by Django 4.2.21 on 2025-06-15 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("growlogs", "0016_remove_growlogentry_notes_alter_growlogcomment_text_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="growlog",
            name="notes",
        ),
    ]
