# Generated by Django 4.2.21 on 2025-06-16 00:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("growlogs", "0018_remove_growlog_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="growlog",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_growlogs", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
