# Generated by Django 4.2.21 on 2025-06-16 00:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("growlogs", "0020_auto_20250616_0045"),
    ]

    operations = [
        # Создаем таблицу для лайков growlogs, если её нет
        migrations.RunSQL(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'growlogs_growlog_likes') THEN
                    CREATE TABLE growlogs_growlog_likes (
                        id serial PRIMARY KEY,
                        growlog_id bigint NOT NULL REFERENCES growlogs_growlog(id) ON DELETE CASCADE,
                        user_id bigint NOT NULL REFERENCES users_user(id) ON DELETE CASCADE,
                        UNIQUE(growlog_id, user_id)
                    );
                    CREATE INDEX growlogs_growlog_likes_growlog_id_idx ON growlogs_growlog_likes(growlog_id);
                    CREATE INDEX growlogs_growlog_likes_user_id_idx ON growlogs_growlog_likes(user_id);
                END IF;
            END $$;
            """,
            reverse_sql="DROP TABLE IF EXISTS growlogs_growlog_likes;"
        ),
    ]
