# Generated by Django 4.2.21 on 2025-06-15 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("growlogs", "0021_auto_20250616_0047"),
    ]

    operations = [
        # Фальшивое удаление поля (только в state, не в БД - поле уже удалено)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="growlogentry",
                    name="notes",
                ),
            ],
            database_operations=[
                # Ничего не делаем в БД - поле уже удалено
            ],
        ),
    ]
